### ISSUE TITLE
Clarify if the red-zone is safe from clobbering by system calls

### ISSUE THREAD

**Issue by pcordes** [hjl-tools/x86-psABI#3]
The current ABI only seems to say that the Red Zone is safe from interrupt and signal handlers, with no mention of `syscall`.  It talks about it allowing leaf functions to save instructions, but one could potentially argue either way that a syscall wrapper is or isn't a leaf function.

I'm pretty sure that Linux doesn't clobber the Red Zone during system calls, and I assume other OSes that use the ABI also behave that way.

So it would be good for the ABI to make this more explicit.  (See for example [this doubt about the safety](http://stackoverflow.com/questions/38823544/recvfrom-using-stack-as-buffer-len4096?noredirect=1#comment65074664_38823544)).

If possible, guaranteeing that no other sources of asynchronous modification are possible would be good.  (e.g. is it true that a POSIX process with no signal handlers has an effectively unlimited-size red-zone?  However, this would apply to 32-bit as well, and may be a well-known fact documented somewhere else, and not belong in this ABI doc.)

**Comment by hjl-tools** [comment]
The x86-64 psABI issue should be discussed at

https://groups.google.com/forum/#!forum/x86-64-abi
