### ISSUE TITLE
(i386): Description of _Bool in registers (outside of arg-passing) is overly specific and confusing.

### ISSUE THREAD

**Issue by pcordes** [hjl-tools/x86-psABI#5]
In the i386 psABI, section 2.1.1 Data Representation,

> Booleans, when stored in a memory object, are stored as single byte objects the
value of which is always 0 (false) or 1 (true). When stored in integer registers
(except for passing as arguments), all 4 bytes of the register are significant; any
nonzero value is considered true.

This seems to imply that *returning* a boolean in a register doesn't have to booleanize, so `_Bool f(int i){return i;}` could just load `i` from the stack into `%eax` and return.  Other sections distinguish between passing and returning.

I think what it's trying to say is that you can do whatever you want in registers, just make sure you booleanize before storing to memory or passing/returning.  I don't know why it tries to say anything about this, since it's only relevant when examining registers with a debugger.

As written, it disallows something like   test / `setc %al` / test / `setz %dl` / `or %dl, %al` / `jnz ...` or store `%al` to memory, because the boolean value is only in the low 8, not zero extended.  (clang sometimes does stuff like this without first `xor`-zeroing the registers or using `movzx` after.)  And even setcc / movzx is disallowed, because the value would exist in a register not zero-extended for one instruction.

The ABI has no place specifying what a function does internally.  I propose deleting the extra wording, since there's nothing to say other than "see the parameter passing section for passing/returning values in registers":

> Booleans, when stored in a memory object, are stored as single byte objects the
value of which is always 0 (false) or 1 (true).

**Comment by pcordes** [comment]
The x86-64 ABI has the same language, in section 3.1.2 Data Representation.

related: https://stackoverflow.com/questions/47243955/boolean-values-as-8-bit-in-compilers-are-operations-on-them-inefficient

**Comment by hjl-tools** [comment]
Please raise the x86-64 psABI issue at

https://groups.google.com/forum/#!forum/x86-64-abi

and the ia32 psABI issue at

https://groups.google.com/forum/#!forum/ia32-abi
